### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by Pangu-Immortal** [lygttpod/AndroidMonitor#1]
Could not initialize class com.intellij.protobuf.lang.PbParserDefinition
集成后一直报错，无法运行。
项目并未使用protobuf，此插件是否对protobuf有要求。
集成环境是否需要配置protobuf才可以使用？？
望修复！！

**Comment by lygttpod** [comment]
@Pangu-Immortal 库中没有使用protobuf相关代码哦，确认一下是否因为集成此库之后才导致无法运行，请提供更多的报错信息吧

**Comment by Pangu-Immortal** [comment]
> @Pangu-Immortal 库中没有使用protobuf相关代码哦，确认一下是否因为集成此库之后才导致无法运行，请提供更多的报错信息吧

注释掉这个库就好了，但是放开这个库之后依然报错。
我的环境信息：
compose_version = '1.2.0-beta03'
id 'org.jetbrains.kotlin.android' version '1.6.21' apply false

compileSdk 32
minSdk 23
targetSdk 30

**Comment by lygttpod** [comment]
@Pangu-Immortal 试了模拟你的环境，也找多很多项目集成测试，并没有出现你这个编译错误哦，可以新建项目或者切换其他项目再试试，如果可以的话提供更多错误信息哦

**Comment by lygttpod** [comment]
@Pangu-Immortal 
升级新版本再试下
**monitor ---> 0.0.9**         
**monitor-plugin  ---> 0.0.2**
