### ISSUE TITLE
把项目抽取成子模块引入，无法抓到接口

### ISSUE THREAD

**Issue by wumeixinjiazu** [lygttpod/AndroidMonitor#11]
我把AndroidMonitor相关的代码都抽到一个模块里（lib_monitor），但是发现无法抓到接口。代码如下：
`apply plugin: 'monitor-plugin'

buildscript {
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        //monitor-plugin需要
        classpath 'io.github.lygttpod:monitor-plugin:0.0.1'
    }
}
dependencies {
    implementation 'io.github.lygttpod:monitor:0.0.4'
}`
然后在app（build.gralde），引入上面的模块
implementation project(':lib_monitor')

运行代码后，抓包App也安装成功了，但就是没有抓到链接。

**Comment by lygttpod** [comment]
@wumeixinjiazu 
自己抽到单独模块的话要确保包名不变才行，因为monitor-plugin会去自动插桩，获取的是com.lygttpod.monitor.MonitorHelper包下面的类。如要一定定要变更包名，请修改monitor-plugin源码，插桩相关代码如下
``` kotlin
            it.visitVarInsn(ALOAD, 0)
            it.visitFieldInsn(GETFIELD, "okhttp3/OkHttpClient\$Builder", "interceptors", "Ljava/util/List;")
            it.visitFieldInsn(GETSTATIC, "com/lygttpod/monitor/MonitorHelper", "INSTANCE", "Lcom/lygttpod/monitor/MonitorHelper;")
            it.visitMethodInsn(INVOKEVIRTUAL, "com/lygttpod/monitor/MonitorHelper", "getHookInterceptors", "()Ljava/util/List;", false)
            it.visitMethodInsn(INVOKEINTERFACE, "java/util/List", "addAll", "(Ljava/util/Collection;)Z", true)
            it.visitInsn(POP)
```

**Comment by wumeixinjiazu** [comment]
包名没有改，我还是通过implementation方式引进的代码。

**Comment by wumeixinjiazu** [comment]
> @wumeixinjiazu 自己抽到单独模块的话要确保包名不变才行，因为monitor-plugin会去自动插桩，获取的是com.lygttpod.monitor.MonitorHelper包下面的类。如要一定定要变更包名，请修改monitor-plugin源码，插桩相关代码如下
> 
> ```kotlin
>             it.visitVarInsn(ALOAD, 0)
>             it.visitFieldInsn(GETFIELD, "okhttp3/OkHttpClient\$Builder", "interceptors", "Ljava/util/List;")
>             it.visitFieldInsn(GETSTATIC, "com/lygttpod/monitor/MonitorHelper", "INSTANCE", "Lcom/lygttpod/monitor/MonitorHelper;")
>             it.visitMethodInsn(INVOKEVIRTUAL, "com/lygttpod/monitor/MonitorHelper", "getHookInterceptors", "()Ljava/util/List;", false)
>             it.visitMethodInsn(INVOKEINTERFACE, "java/util/List", "addAll", "(Ljava/util/Collection;)Z", true)
>             it.visitInsn(POP)
> ```

包名没有改，我还是通过implementation方式引进的代码。我想拆分成一个模块把所有相关的东西导入。并没有把源码文件复制进来。

**Comment by lygttpod** [comment]
@wumeixinjiazu 我验了一下，插件还是要在主项目中加的，在子模块中是无效的，插件加在哪个模块只会在哪个模块中去hook代码，所以主项目不加的话就没有去hook代码就出现只有入口没有数据的情况
