### ISSUE TITLE
io.github.lygttpod:monitor-plugin:0.0.1 提示找不到

### ISSUE THREAD

**Issue by petterEat** [lygttpod/AndroidMonitor#16]

**Comment by lygttpod** [comment]
请参照demo或者说明文档进行重新配置，如果还是不行，请贴出错位日志

**Comment by lygttpod** [comment]
升级新版本试试
      
**monitor ---> 0.0.9**         
**monitor-plugin  ---> 0.0.2**

**Comment by petterEat** [comment]
这个插件上传到哪个库了，mavenCentral找不到&gt; Could not resolve all files for configuration ':app:debugRuntimeClasspath'.    &gt; Could not resolve io.github.lygttpod:monitor:0.0.9.      Required by:          project :app       &gt; Could not resolve io.github.lygttpod:monitor:0.0.9.          &gt; Could not get resource 'https://maven.google.com/io/github/lygttpod/monitor/0.0.9/monitor-0.0.9.pom'.             &gt; Could not HEAD 'https://maven.google.com/io/github/lygttpod/monitor/0.0.9/monitor-0.0.9.pom'.                &gt; Connect to maven.google.com:443 [maven.google.com/172.217.160.78] failed: connect timed out




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月29日(星期二) 下午5:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lygttpod/AndroidMonitor] io.github.lygttpod:monitor-plugin:0.0.1 提示找不到 (Issue #16)





 
升级新版本试试
 
monitor ---&gt; 0.0.9
 monitor-plugin  ---&gt; 0.0.2

**Comment by lygttpod** [comment]
@petterEat
 https://s01.oss.sonatype.org/service/local/repositories/releases/content/io/github/lygttpod/monitor/0.0.9/monitor-0.0.9.pom
![image](https://user-images.githubusercontent.com/11826777/205250874-67c6648b-7fda-4958-b597-49267475a232.png)

**Comment by lygttpod** [comment]
@petterEat 
你clone下源码，跑一下demo 看看依赖有没有问题吧
