### ISSUE TITLE
请求参数也可复制

### ISSUE THREAD

**Issue by JasonYinH** [lygttpod/AndroidMonitor#18]
![image](https://user-images.githubusercontent.com/40187930/188557659-8264c2b4-805d-4ebf-82e7-f0a26fa9d574.png)
现在请求参数传的太多，希望加个复制功能，pc

**Comment by lygttpod** [comment]
升级新版本
      
**monitor ---> 0.0.9**         
**monitor-plugin  ---> 0.0.2**
