### ISSUE TITLE
应该升级最新的Android studio 工程。

### ISSUE THREAD

**Issue by Pangu-Immortal** [lygttpod/AndroidMonitor#2]
我查看了你的源代码。请移除如下依赖库后重新封装。guava和protobuf问题很多，问题都在如下第三方库里。

  模块  【include ':monitor'】

//  安卓本地微服务架构
    def als_version = "0.0.1"
    implementation "io.github.lygttpod.android-local-service:core:$als_version"
    implementation "io.github.lygttpod.android-local-service:annotation:$als_version"
    kapt "io.github.lygttpod.android-local-service:processor:$als_version"

<img width="563" alt="image" src="https://user-images.githubusercontent.com/13057690/179937847-4e904500-c8fb-4448-97bb-4f6ec4016854.png">

**Comment by Pangu-Immortal** [comment]
详细日志如下：

> Task :monitor:compileDebugJavaWithJavac
The following annotation processors are not incremental: processor-0.0.1.jar (io.github.lygttpod.android-local-service:processor:0.0.1).
Make sure all annotation processors are incremental to improve your build speed.
注: /Users/lili/AndroidStudioProjects/AndroidMonitor/monitor/build/generated/source/kapt/debug/com/lygttpod/monitor/service/ALS_MonitorService.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

Could not initialize class com.intellij.protobuf.lang.PbParserDefinition

BUILD SUCCESSFUL in 16s
59 actionable tasks: 39 executed, 20 up-to-date

**Comment by lygttpod** [comment]
检查了android-local-service库，并没有使用pb相关库

```
+--- project :core (*)
+--- org.nanohttpd:nanohttpd:2.2.0
+--- org.jetbrains.kotlin:kotlin-stdlib:1.4.32
|    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.4.32
|    \--- org.jetbrains:annotations:13.0
\--- com.google.code.gson:gson:2.8.6
```

```
+--- project :annotation
\--- com.squareup:javapoet:1.13.0
```
