### ISSUE TITLE
最新版，抓包app抓包内容都是空的是为什么

### ISSUE THREAD

**Issue by FrankLove** [lygttpod/AndroidMonitor#22]

**Comment by lygttpod** [comment]
贴下如何集成的相关代码吧

**Comment by FrankLove** [comment]
按照readme里面的三个步骤集成的

**Comment by FrankLove** [comment]
![image](https://user-images.githubusercontent.com/8580868/224619119-c5fbf984-c276-4f28-bcfd-01f7cac51319.png)
![image](https://user-images.githubusercontent.com/8580868/224619184-8deb87bc-842d-4e90-8ae5-ff8301bde8cd.png)
![image](https://user-images.githubusercontent.com/8580868/224619231-5b49eed3-eaed-4899-a364-4a1f9233b5db.png)

**Comment by lygttpod** [comment]
请使用最新版本 **_V0.1.1_**  在试试
```
   debugImplementation 'io.github.lygttpod:monitor:0.1.1'
```
