### ISSUE TITLE
duplicate entry: META-INF/maven/com.belerweb/pinyin4j/pom.xml

### ISSUE THREAD

**Issue by langxing** [lygttpod/AndroidMonitor#25]
java.util.zip.ZipException: duplicate entry: META-INF/maven/com.belerweb/pinyin4j/pom.xml

跑不起来，报这个错，是什么问题呢？

**Comment by lygttpod** [comment]
@langxing 试试这个 [pinyin4j Issues解决方案](https://github.com/belerweb/pinyin4j/wiki/%E5%BC%80%E5%8F%91android-%E7%9A%84%E5%B0%8F%E4%BC%99%E4%BC%B4-%E9%81%87%E5%88%B0%E7%9A%84bug)
