### ISSUE TITLE
是否依赖了com.github.lygttpod.ShapeView:1.0.2

### ISSUE THREAD

**Issue by JasonYinH** [lygttpod/AndroidMonitor#26]
添加抓包报错
![1`DBTAR)R50DZ91 LTACKJ](https://github.com/lygttpod/AndroidMonitor/assets/40187930/8289dca3-20dc-4bad-bd7b-3fe3a875e906)

**Comment by lygttpod** [comment]
是的，依赖 [ShapeView](https://github.com/lygttpod/ShapeView)


先在项目根目录的 build.gradle 的 repositories 添加:
```
     allprojects {
         repositories {
            ...
            maven { url "https://jitpack.io" }
        }
    }
```
然后在dependencies添加:
```
        dependencies {
            implementation 'com.github.lygttpod:ShapeView:VERSION_CODE'
        }
```
