### ISSUE TITLE
佬，有时间看下吧

### ISSUE THREAD

**Issue by JasonYinH** [lygttpod/AndroidMonitor#27]
https://juejin.cn/post/7119083753376317448

**Comment by JasonYinH** [comment]
![image](https://github.com/lygttpod/AndroidMonitor/assets/40187930/2b0715f4-8102-4585-a974-49c1d6fb0313)
F12 看把数据都查出来了，但是网页上不显示

**Comment by JasonYinH** [comment]
![image](https://github.com/lygttpod/AndroidMonitor/assets/40187930/32a46598-8dc6-4d36-a70f-a6c887d744e5)

**Comment by JasonYinH** [comment]
google、火狐游览器，版本都是最新的

**Comment by lygttpod** [comment]
问题已修复，请使用最新版 **v0.1.1** 体验一下
```
   debugImplementation 'io.github.lygttpod:monitor:0.1.1'
```
