### ISSUE TITLE
最新版本下载不下来0.1.1

### ISSUE THREAD

**Issue by JasonYinH** [lygttpod/AndroidMonitor#28]

**Comment by lygttpod** [comment]
**检查一下网络吧，这边试了一下是可以下载的**

![monitor](https://github.com/lygttpod/AndroidMonitor/assets/11826777/2597a721-8629-45c1-9a88-15e0ac991bf1)

**Comment by JasonYinH** [comment]
今天能下载下来了，pc端能看到数据了，感谢大佬。
