### ISSUE TITLE
dayjs is not defined   ，Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by JasonYinH** [lygttpod/AndroidMonitor#29]
![image](https://github.com/lygttpod/AndroidMonitor/assets/40187930/040a754c-e651-4579-81f9-b9e81e2d61db)

**Comment by JasonYinH** [comment]
经常出现

**Comment by lygttpod** [comment]
dayjs移除了，请依赖 v0.1.2
