### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Glorylan** [lygttpod/AndroidMonitor#6]
app的build.grdle添加：
//1、依赖抓包插件库
        classpath 'io.github.lygttpod:monitor-plugin:0.0.1'
根build.grdle添加：
//2、应用抓包插件
    id 'monitor-plugin'
//3、依赖抓包库 只在debug环境下依赖  所有使用 debugImplementation
    debugImplementation 'io.github.lygttpod:monitor:0.0.5'
报错信息：
Execution failed for task ':app:transformClassesWithOkHttpTransformForDebug'.
> java.util.zip.ZipException: zip file is empty
无具体提示哪个目录为空

**Comment by Glorylan** [comment]
![image](https://user-images.githubusercontent.com/14041103/186558829-3bc26042-faa0-4587-8f3d-25b1024180a7.png)

**Comment by lygttpod** [comment]
升级新版本试下
      
**monitor ---> 0.0.9**         
**monitor-plugin  ---> 0.0.2**
