### ISSUE TITLE
没有映射的域名要怎么配置才能抓到包，目前我链接的内网ip地址，抓不到网络.

### ISSUE THREAD

**Issue by wumeixinjiazu** [lygttpod/AndroidMonitor#7]

**Comment by lygttpod** [comment]
纯IP地址请求过滤了，因为一些三方平台比如 阿里云部分服务分配的是纯IP地址，这部分其实不需要抓取的，故而过滤了，没想到你们自己的纯IP地址，近期会加个参数控制是否抓取纯IP地址的请求，请关注最新动态

**Comment by wumeixinjiazu** [comment]
![image](https://user-images.githubusercontent.com/36200075/186560725-d133774a-06f8-4f2b-949e-064544638b09.png)
在这里控制就好了。

**Comment by lygttpod** [comment]
升级0.0.7版本试一下
[V0.0.7更新说明](https://github.com/lygttpod/AndroidMonitor/releases/tag/0.0.7)
