### ISSUE TITLE
大佬，用你的rxhttp库请求怎么抓不到包呢，内网地址

### ISSUE THREAD

**Issue by FrankLove** [lygttpod/AndroidMonitor#9]

**Comment by lygttpod** [comment]
内网是IP地址吗，是IP地址的话我默认是禁止抓IP地址的请求的，因为一些三方平台比如 阿里云部分服务分配的是纯IP地址，这部分其实不需要抓取的，故而过滤了，近期会加个参数控制是否抓取纯IP地址的请求，请关注最新动态

**Comment by lygttpod** [comment]
@FrankLove 升级0.0.7版本试一下
[V0.0.7更新说明](https://github.com/lygttpod/AndroidMonitor/releases/tag/0.0.7)
